py_binary (
    name = "main",
    srcs = glob(["*.py"]),
#    srcs_version = "PY3",
)

#py_runtime (
#    name = "Python 3.6.3",
#    files = [],
#    interpreter_path = "/home/hides/.pyenv/versions/anaconda3-5.0.1/bin/python",
#)